
name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0
      - name: print working directory 
        run: ls -R
      - name: Install dependencies
        run: |
          cd front-end
          npm install
          cd ..
          cd backend
          npm install
          cd ..
      - name: Build frontend
        run: |
          cd front-end
          npm run build
          cd ..
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo $HEROKU_API_KEY | heroku auth:token
          heroku git:remote -a ecom-fashion-server
          git subtree push --prefix backend heroku main
