name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0
      
      - name: Install dependencies
        run: |
          cd front-end && npm install
          cd ../backend && npm install
      
      - name: Build frontend
        run: |
          cd front-end && npm run build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
      
      - name: Commit frontend build to backend
        run: |
          pwd
          cd backend/public
          git add .   
          git commit -m "Update frontend build" || echo "No changes to commit"
          cd ../../  
      
      - name: Deploy backend to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ecom-fashion-server
          heroku_email: kbrianmutai@gmail.com
          appdir: backend
