name: Deploy to Heroku
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 22.2.0

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Deploy backend to Heroku
      - uses: akhileshns/heroku-deploy@v3.13.15
       
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ecom-fashion-server
          heroku_email: kbrianmutai@gmail.com
          appdir: "backend"

      
